### ISSUE TITLE
Viewer settings thread safety

### ISSUE THREAD

**Issue by akortunov** [openscenegraph/OpenSceneGraph#1057]
Hello. In OpenMW we need a way to disable/enable main scene when we render splash screen. So far we save "normal" cull/update settings and temporarily override them:

```
    void WindowManager::enableScene(bool enable)
    {
        unsigned int disablemask = Mask_GUI;
        if (!enable && mViewer->getCamera()->getCullMask() != disablemask)
        {
            mOldUpdateMask = mViewer->getUpdateVisitor()->getTraversalMask();
            mOldCullMask = mViewer->getCamera()->getCullMask();
            mViewer->getUpdateVisitor()->setTraversalMask(disablemask);
            mViewer->getCamera()->setCullMask(disablemask);
        }
        else if (enable && mViewer->getCamera()->getCullMask() == disablemask)
        {
            mViewer->getUpdateVisitor()->setTraversalMask(mOldUpdateMask);
            mViewer->getCamera()->setCullMask(mOldCullMask);
        }
    }
```

Since we use "Draw thread per context" model, ideally used approach should affect only the frame which main thread processes now, not a previous one which draw thread renders. So far it does not seem to be a thing, and we get thread sanitizer warnings when we try to change camera settings in the main thread.

Is it safe to modify viewer settings in the "Draw thread per context" mode? Are there better ways to temporarily disable part of scene? Set target node mask to 0, maybe?

**Comment by robertosfield** [comment]
The best place for support questions is the osg-users googegroup as it'll be seen by the most users.

W.r.t enabling/disabling update, cull and draw, the application has complete control over when you call viewer.frame() or the constituent parts viewer.advance(), viewer.updateTraversal(), viewer.eventTraversal() and viewer.renderingTraversals() so you could just not bother to call these when you don't want to render,  

If you do want to go the path of modify cull mask settings then this should work and as long shouldn't cause any thread issues as long as they are called in the update phase of the scene graph i.e. not while renderingTraversals() is being run.

**Comment by AnyOldName3** [comment]
For a little bit of context, all we want to do is temporarily disable the bits of the cull mask that correspond to the 3D scene during load screens while leaving the GUI bit enabled so you actually see the loading screen. Based on posts like https://groups.google.com/g/osg-users/c/b6jRdrzuJWs/m/Z4AG2OUIOCYJ, we believe this is something the OSG's supposed to support as long as it's during the update traversal, even with DrawThreadPerContext, where there'd be a draw traversal potentially happening in parallel.

While the cull mask is only accessed in the cull traversal, so would be safe to change during the update traversal, which never happens at the same time, that's not the only thing that `osg::Camera::setCullMask` changes - it also modifies the inheritance mask, which *is* accessed during the draw phase. That would mean that it's not enough to only change the cull mask during the update traversal - we'd have to also delay the update traversal until after the previous draw traversal had completed. I'm aware it's not the same bits of the inheritance mask that get edited as get read during the draw traversal, but I'm reasonably sure C++ makes no guarantees that a write from another thread won't temporarily make other bytes of the same int undefined, and TSAN agrees.

If calling `osg::Camera::setCullMask` is supposed to be safe to do during the update traversal while a draw traversal is in flight (which we believe was your intention), then there's a bug here that you should be aware of, and could fix (e.g. by splitting the inheritance mask into two variables, one of which holds just the parts which are safe to modify while a draw traversal is in flight, and the other of which holds the rest). Otherwise, we have other approaches we could use, but it would be a good idea to add some clarification to the linked mailing list thread as that's what Google returns when querying `osg::Camera::setCullMask` thread safety, and it's misleading if it's not actually safe.

**Comment by openscenegraph** [comment]
Where is the inheritance mask being accessed in draw?

As a general comment, for one off changes that might not be thread safe you
can always switch off threading during that phase then re-enable.

There are lots of different ways to tackle the task you have, I wouldn't
have thought there would be any need to modify the core.

**Comment by akortunov** [comment]
> Where is the inheritance mask being accessed in draw?

At least `osgUtil::SceneView::draw()` works with it.

**Comment by openscenegraph** [comment]
On Fri, 19 Mar 2021 at 17:23, Andrei Kortunov ***@***.***>
wrote:

> Where is the inheritance mask being accessed in draw?
>
> At least osgUtil::SceneView::draw() works with it.
>

Thanks for the pointer.

The Camera CullSettings set/get settings are provided by the
osg::CullSettings class which provides control over whether those settings
should be passed on to the inheritance mask, so you could look at these.  I
don't know the specifics of your application so can't say whether it'll
have any negative consequences for your usage case.

       enum InheritanceMaskActionOnAttributeSetting
        {
            DISABLE_ASSOCIATED_INHERITANCE_MASK_BIT,
            DO_NOT_MODIFY_INHERITANCE_MASK
        };

        void
setInheritanceMaskActionOnAttributeSetting(InheritanceMaskActionOnAttributeSetting
action) { _inheritanceMaskActionOnAttributeSetting = action; }
        InheritanceMaskActionOnAttributeSetting
getInheritanceMaskActionOnAttributeSetting() const { return
_inheritanceMaskActionOnAttributeSetting; }

        /** Apply the action, specified by the
InheritanceMaskActionOnAttributeSetting, to apply to the inheritance bit
mask.
          * This method is called by CullSettings::set*() parameter methods
to ensure that CullSettings inheritance mechanisms doesn't overwrite the
local parameter settings.*/
        inline void applyMaskAction(unsigned int maskBit)
        {
            if
(_inheritanceMaskActionOnAttributeSetting==DISABLE_ASSOCIATED_INHERITANCE_MASK_BIT)
            {
                _inheritanceMask = _inheritanceMask & (~maskBit);
            }
        }
