### ISSUE TITLE
You should really disable all vertex attribs in State::disableAllVertexArrays.

### ISSUE THREAD

**Issue by vengine** [openscenegraph/OpenSceneGraph#1076]
On line 1112 of **State.cpp**, you only disable the first vertex array as "**disableVertexAttribPointersAboveAndIncluding(0);**",
but when I used more than one vertex attribs, only one vertex attrib is disabled, that caused same render error like strange color on geometries.
I think you should really disable all vertex attribs in **State::disableAllVertexArrays**.

**Comment by vengine** [comment]
```cpp
void State::disableAllVertexArrays()
{
    disableVertexPointer();
    disableColorPointer();
    disableFogCoordPointer();
    disableNormalPointer();
    disableSecondaryColorPointer();
    disableTexCoordPointersAboveAndIncluding(0);
    disableVertexAttribPointersAboveAndIncluding(0); // this line causes the problem
}
```

**Comment by openscenegraph** [comment]
On Fri, 6 Aug 2021 at 01:25, vengine ***@***.***> wrote:

> void State::disableAllVertexArrays()
> {
>     disableVertexPointer();
>     disableColorPointer();
>     disableFogCoordPointer();
>     disableNormalPointer();
>     disableSecondaryColorPointer();
>     disableTexCoordPointersAboveAndIncluding(0);
>     disableVertexAttribPointersAboveAndIncluding(0); // this line causes the problem
> }
>
> This line you refer to is "disableVertexAttribPointersAboveAndIncluding(0)"
which if you read it correctly means disable all vertex attributes.

As to why things aren't working for you please provide an example that
others can compile and run and see the problem, otherwise we are just
guessing what you have done, the problem may well just be in your code.
