### ISSUE TITLE
How to discard the Alt key when scroll?

### ISSUE THREAD

**Issue by msnh2012** [openscenegraph/OpenSceneGraph#1239]
Currently, when I press the alt key and scroll my mouse, OSG always scrolls to one side. How can I fix this? 
(Or where is the code that causes this issue?)
Thx.

**Comment by robertosfield** [comment]
? OSG always scrolls to one side??

What bit of the OSG are you talking about?  Are you talking about a standard camara manipulator?  

I don't recall any of them use the alt key so you'll need to be specific about what you are talking about otherwise there is no way anyone will be able to help you.

**Comment by msnh2012** [comment]
I double check my code, I found the key to this issue finally. It's Qt's new mouse scroll API that has changed.  I'll close this issue. 
Thx.
