### ISSUE TITLE
http://api.mapbox.com/v4/mapbox.satellite/0/0/0.jpg?access_token=xxxxxxxxx : file not handled

### ISSUE THREAD

**Issue by ozhanghe** [openscenegraph/OpenSceneGraph#1320]
When I open the URL in the browser, it loads an image. Why doesn't OSG load it properly.

Error In: https://github.com/Prograda/Skybolt/blob/master/src/Skybolt/SkyboltVis/Renderable/Planet/Tile/TileSource/XyzTileSource.cpp

**Comment by robertosfield** [comment]
I'm not familiar with Skybolt project.  Have you asked the support question there?

Best guess on scant information is that perhaps the OSG is not being set up to handle to particular URL string in the way that is required.  The OSG's plugin mechanism matches the filename extension to the ReaderWrite plugin that will load the file, the extension is the part of the flename after the . which is malformed w.r.t .jpg.

The way around this is to preload the jpg plugin and explicitly call it to read the file, but as this is a http file the curl plugin will need to be invoked first, then the jpeg plugin.

This steps are things I would expect Skybolt to do, it's really a high level problem rather than a low level OSG one.
