### ISSUE TITLE
Pragma(tic) shader composition generates invalid shader text with CRLF line endings

### ISSUE THREAD

**Issue by siu** [openscenegraph/OpenSceneGraph#360]
We are refactoring some code to load shaders using the new pragma shader composition. Some more context to understand the problem:

 * We load the shader text from a text file
 * This comes from a git repository and git (by default) converts the line endings to the platform line endings. On windows CRLF and on unixes LF.
 * This works fine if we don't use the new setDefine(..., ...)
 * I am testing on nvidia hardware + drivers

As soon as we use defines the shader code is split in several blocks, one with the glsl version, one with the defines and a third one with the rest of the shader source. If the original shader source uses CRLF line endings the produced "#version 150" line becomes "#version 150\r" which does not compile at run-time. Everything works as expected if the line endings are "\r\n".

This is most likely a problem around https://github.com/openscenegraph/OpenSceneGraph/blob/cb2b0a5fe84bf862613b46432226a0201005fced/src/osg/Shader.cpp#L611

I can contribute a fix but I would like to know what is the preferred approach:

1. Convert "\r\n" line endings to "\n" in osg::Shader::setSource(...)
2. Handle "\r\n" in osg::Shader::PerContext::compileShader(...) 
3. "\r\n" are not supported and the documentation of osg::Shader needs to be updated. The client code must provide the correct line endings.

Also we need the fix in the stable version, do you accept patches to 3.4 or only to master?

**Comment by openscenegraph** [comment]
What a pain these type of issues are, platform incompatibilities that stem from stupid decisions by MS and alike many years ago but still plaguing us today... life would be so much simpler if all platforms just adopted the LF standard of Unix.

The Shader.cpp file has diverged a bit between 3.4 and master so we might need to different patches.  My inclination, rather than change user source via a setSource() change, is to fix it in compileShader or in osg::State though I'd have to look at all relevant code to make a decision though.  I am busy with other tasks right now so can't investigate right away.  If you have a fix then generate a PR and I can can review the changes, this will give me a feel form what is likely to be required if not the final solution.

**Comment by siu** [comment]
Thanks for the input, I will see if I can provide a patch.
