### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [openscenegraph/OpenSceneGraph#395]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by openscenegraph** [comment]
I have passed the contents this topic to the osg-users mailing list/forum to see if any of the community are interested.

I am closing this topic here as it's just a announcement for a 3rd party project, rather than any genuine issue with the OSG itself, you know stuff like bugs, stuff that goes into Issue trackers.

**Comment by remoe** [comment]
An alternative is a CMake based System: https://github.com/ruslo/hunter
