### ISSUE TITLE
osgversion: spurious output

### ISSUE THREAD

**Issue by filnet** [openscenegraph/OpenSceneGraph#401]
```
$ osgversion --version-number
DisplaySettings::SHADER_GL3
3.5.10
```

This breaks tools.

**Comment by openscenegraph** [comment]
This is not spurious output,  it's important information about the GL implementation that's be selected at runtime.  

This output is from a development release of the OpenSceneGraph, output information is more verbose to help us track causes of regressions that might appear.  As we approach stable releases the level of this type of output is toned down.

**Comment by filnet** [comment]
Ok. I understand.

I just wanted to point out that this additional output throws of build chains that rely on osgversion to find out the OSG version.
May be there is a way to totally silence debug output when osgversion is running (or at least when the --version-number arg is given).

**Comment by robertosfield** [comment]
You don't got the DisplaySettings::SHADER_* output if you build and run the OSG with defaults, so I presume you've either built the OSG specifically for GL3 or used the OSG_SHADER_HINT env var to enable GL3 shaders.

You can suppress the output by setting the notify level to ALWAYS thus:

export OSG_NOTIFY_LEVEL=ALWAYS
osgversion

Once shader setup functionality has settled down in the core OSG it won't be necessary to output that the OSG is not using defaults and the SHADER_HINT message will become INFO rather than NOTICE.

**Comment by filnet** [comment]
Yes, I was trying a build with OPENGL_PROFILE=CORE.

Will use OSG_NOTIFY_LEVEL=ALWAYS. Thanks for the tip.
