### ISSUE TITLE
osgText::Text: virtual assignStateSet() method called inside constructor

### ISSUE THREAD

**Issue by valid-ptr** [openscenegraph/OpenSceneGraph#460]
The only one way to disable default osg::Text's shaders (if OSG build without OSG_GL_FIXED_FUNCTION_AVAILABLE) is to create derived class...

**Text.cpp lines 216-225:**
```
    #if defined(OSG_GL_FIXED_FUNCTION_AVAILABLE)
    osg::DisplaySettings::ShaderHint shaderHint = osg::DisplaySettings::instance()->getShaderHint();
    if (_shaderTechnique==NO_TEXT_SHADER && shaderHint==osg::DisplaySettings::SHADER_NONE)
    {
        DEBUG_MESSAGE<<"Font::Font() Fixed function pipeline"<<std::endl;

        stateset->setTextureMode(0, GL_TEXTURE_2D, osg::StateAttribute::ON);
        return stateset.release();
    }
    #endif
```

But! There is a surprise!!! :)
virtual method call inside constructor, so osgText::Text will create it's own stateset with Program and so on.

PS
[Stack Overflow: Calling virtual functions inside constructors](https://stackoverflow.com/questions/962132/calling-virtual-functions-inside-constructors)

**Comment by openscenegraph** [comment]
You can set the shader hint by calling osg::DisplaySettings::instance()->setShaderHint(osg::DisplaySetting::SHADER_NONE) prior to any of the osgText elements are constructed.

As for the virual function being called from the constructor - this isn't the base class constructor, it's being called by the subclass, so while it's not ideal C++ usage I don't believe this is any danger.  If it does cause problems then the way to resolve it would be to replace the assignStateSet() with a setStateSet(Text::createStateSet());.  

Unless there is actual problem is found I don't see the need to for any changes as things stand.
