### ISSUE TITLE
TGA reader sets invalid internal format

### ISSUE THREAD

**Issue by matthew-reid** [openscenegraph/OpenSceneGraph#471]
The TGA reader sets the internal format to the number of colour channels, which as far as I know is not a valid OpenGL internal format.

https://github.com/openscenegraph/OpenSceneGraph/blob/5ff16798a354c9e7ce6776dfa22162fd0e83efff/src/osgPlugins/tga/ReaderWriterTGA.cpp#L567

**Comment by openscenegraph** [comment]
Historically GL drivers have accepted the number of components as valid internal format - which is why the code is doing what is.  I don't recall the details but I think either GLES or some modern GL drivers don't necessarily support this mapping.  Mapping the number of components to a pixel format is probably appropriate for this code.

What GL/GLES versions are you working with?  Have you see specific GL errors associated with TGA files?

**Comment by openscenegraph** [comment]
I have checked in the following commit to master and the OpenSceneGraph-3.4 branches:

https://github.com/openscenegraph/OpenSceneGraph/commit/22d6ce826f7b2a4d3526d649740a6294351fe9e7

**Comment by matthew-reid** [comment]
Thanks. Your change makes sense. I'm using GL 4 and didn't see any specific errors from GL, but my own code doesn't expect old internal format values and I couldn't see them documented anywhere.
