### ISSUE TITLE
Vanishing letters in osg::Text

### ISSUE THREAD

**Issue by moulinfr** [openscenegraph/OpenSceneGraph#481]
I noticed that a bug mentionned in http://forum.openscenegraph.org/viewtopic.php?t=16636 is still present for Intel HD cards for OSG releases 3.5.[6-9]. It works properly on version 3.4.1 however.

The driver of my graphical adapter is up-to-date; please find some details here:
 - Windows 10 Enterprise 64-bit
 - Intel HD4600 20.19.15.4835
 - compiled with MSVC 2017 x64

Same issue appears on Windows Surface Pro and other Windows PC with various Intel graphical cards.

Given that the rendering of osgText changed a lot since then, I was not able to apply the fix proposed in the OSG forum, and I am not an OpenGL specialist too... Please, could you confirm the bug and provide us with a correction if needed?

Thank you for your help.

**Comment by openscenegraph** [comment]
I don't have Windows Intel system to check against.  Have you tried OSG master?

**Comment by moulinfr** [comment]
No, not yet. I am off for one week, so I will give it a try when I will be back.

Thank you for your fast feedback!

**Comment by openscenegraph** [comment]
I have looked into the orignal PR for 3.4 to see what the key changes are and what it might suggest about issues specific to the Intel drive+hardware combination that was problematic.  What it looks like is that subloading to an existing texture object ignores the filter modes that are previous assigned to the texture object, this looks like a bug in the driver to me.  

I have Intel iCore8 CPU with integrated graphics on my google pixel chromebook that I have installed Linux on and it works fine with the latest rev of the OSG so this suggests that the driver bug may well be just Windows specific.

As a workaround it may be necessary to modify the Texture2D::apply() method so that always calls the  Texture::applyTexParameters() prior to do the subload of the image, the relevant code in Texture2D.cpp (line 191 to 215 in OSG master) is:

    if (textureObject)
    {
        textureObject->bind(state);

        if (getTextureParameterDirty(state.getContextID()))
            applyTexParameters(GL_TEXTURE_2D,state);

        if (_subloadCallback.valid())
        {
            _subloadCallback->subload(*this,state);
        }
        else if (_image.valid() && getModifiedCount(contextID) != _image->getModifiedCount())
        {
            // update the modified tag to show that it is up to date.
            getModifiedCount(contextID) = _image->getModifiedCount();

            applyTexImage2D_subload(state,GL_TEXTURE_2D,_image.get(),
                                    _textureWidth, _textureHeight, _internalFormat, _numMipmapLevels);
        }
        else if (_readPBuffer.valid())
        {
            _readPBuffer->bindPBufferToTexture(GL_FRONT);
        }

    }

Note, the lines 195/196:

   if (getTextureParameterDirty(state.getContextID()))
            applyTexParameters(GL_TEXTURE_2D,state);

You could try commenting out the if (..) line (line number 195) so that applyTexParameters(..) always gets called.  If this fixes the problem then we can look at how we might better handle this workaround - removing the getTextureParameterDirty() isn't a good solution long term as it will impact performance for most texture usage all because of the driver bug.

**Comment by openscenegraph** [comment]
@moulinfr have you done any testing yet?  I'd like to get to the bottom of the the issue and get any fixes checked if they are required.

**Comment by moulinfr** [comment]
Back to business! Sorry for my late answer... I tested the modification you had suggested and confirm that it works with it.

**Comment by openscenegraph** [comment]
Thanks for the testing, I've checked refactor of the texture parameters in a way that will hopefully work better with these Intel drivers.  Could you test the git master and let me know if things work out of the box without any changes.

The commit with my changes is:
https://github.com/openscenegraph/OpenSceneGraph/commit/7b6eedbdf4b47bbcbc73dc0b62b15c5910326969

**Comment by moulinfr** [comment]
I tested your changes and it works properly. Thank you very much for your help!

**Comment by openscenegraph** [comment]
Great to hear things are now working well
