### ISSUE TITLE
setting UpVector of a Manipulator other than z axis don't have any effect

### ISSUE THREAD

**Issue by mp3butcher** [openscenegraph/OpenSceneGraph#541]
To reproduce:
just setHomePosition of any CameraManipulator with Upvector other than z

Debug info:
CoordinateFrame returned by ViewerCoordinateFrameCallback::getCoordinateFrame(const osg::Vec3d& position) const as no rotation component 
because
 _view->getCoordinateSystemNodePath() is empty then it returns  osg::Matrixd::translate(position) 
and so extracted upVector is always (0,0,1)

I haven't find yet a proper fix for that as it require deepest knowledge of osgGA I don't have

**Comment by openscenegraph** [comment]
It's up to each CameraManipulator what to do with the home settings, and for the up direction different camera manipulators derive the up direction themselves - such as the drive manipulator.   I think you are expect setHomePosition to do more than it can do, so it's an issue of expectation rather than a bug so I'm closing the issue.  

If you want to discuss how you think osgGA could be changed/improved then the best place for these discussion is on osg-users ML/forum.
