### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by 360CodeSafe** [openscenegraph/OpenSceneGraph#572]
applications/present3D/ReadShowFile.cpp  

memory is allocated in line 159, but not freed at the end of function . Potential leak of memory pointed to by 'str'.

**Comment by openscenegraph** [comment]
putenv is implemented differently on different OS's and even within different rev's of the same OS, some while take a copy others don't.  It's rather a mess.  So you can't just say it has a memory leak as if we "fixed" it for one variant of putenv we'd created a dangling pointer on the next.

Given a possible small leak is far better than a dangling pointer and associated crash I believe the code is as good as we can get it without completely removing the use of getenv.   Since present3D is niche OSG application I really don't see this as a high priority so I'm going closing the "Issue" as there is nothing we can do safely to resolve it without major changes to add any us of putenv/getenv.
