### ISSUE TITLE
crash with new VAO path

### ISSUE THREAD

**Issue by mp3butcher** [openscenegraph/OpenSceneGraph#694]
The following code exhibits crash with new VAO path  with my test model.
Please confirm it with yours
```
#include <osgUtil/MeshOptimizers>
#include <osgGA/TrackballManipulator>
#include <osgGA/FirstPersonManipulator>

#include <osgViewer/Viewer>
#include <osgViewer/ViewerEventHandlers>

#include <osgDB/ReadFile>
#include <osgDB/WriteFile>


class GeomLoaderCB : public osg::Camera::DrawCallback//  osg::NodeCallback
{
public:
    int _thresremoval;int _nbaddedatatime;
    GeomLoaderCB(int thresremoval=1,int nbaddedatatime=1):_nbaddedatatime(nbaddedatatime),_thresremoval(thresremoval) {}
    mutable std::list<osg::ref_ptr<osg::Geometry> > _geoms;
    void setGeometryList(osgUtil::GeometryCollector::GeometryList c) {
        for(auto f : c)
            _geoms.push_back(f);
    }
    virtual void operator () (const osg::Camera&  camera ) const {
        osg::Node * node=const_cast<osg::Camera*>(&camera)->getChild(0);

        if(_geoms.empty())return;
        osg::ref_ptr<osg::Group>  gr = node->asGroup();

        if(gr->getNumChildren()>_thresremoval)
        {
            osg::ref_ptr<osg::Geometry> geom = gr->getChild(0)->asGeometry();
            OSG_WARN<<"removing "<< geom.get()<<std::endl;
            gr->removeChildren(0,1);
            /// not changing anything geom->releaseGLObjects(); 
///geom vas is already null before removal!!!
            return;
        }

        std::list<osg::ref_ptr<osg::Geometry> > ::iterator it= _geoms.begin();
        int cpt=0;
        while(it!=_geoms.end()&&cpt++<_nbaddedatatime ) {
            osg::Geometry *newdr=(osg::Geometry*) (*it)->clone(osg::CopyOp::DEEP_COPY_ALL);
            gr->addChild(newdr);
            OSG_WARN<<"add "<< newdr ->getVertexArray()->getNumElements()<<std::endl;
            it=_geoms.erase(it);
        }
        return;
    }
};

/// This demo reproduce a bug with OSG_VERTEX_BUFFER_HINT=VAO
/// it collecte drawables given in arg then add and remove them at runtime
int main(int argc, char **argv)
{
    osg::ArgumentParser args(&argc,argv);
    unsigned int  geomcountaddedatatime=1,geomcountabovewichweremove=1;
    while(args.read("--add",geomcountaddedatatime) ) { }
    while(args.read("--remove",geomcountabovewichweremove) ) { }
    osgUtil::GeometryCollector geomcollector(0,osgUtil::Optimizer::ALL_OPTIMIZATIONS);

    osg::ref_ptr<osg::Node > loaded=osgDB::readNodeFiles(args);
    if(loaded.valid())
    {
        loaded->accept(geomcollector);

        osg::Group * root=new osg::Group;
        GeomLoaderCB * loader=new GeomLoaderCB(geomcountabovewichweremove, geomcountaddedatatime);
        loader->setGeometryList(   geomcollector.getGeometryList() );

        osgViewer::Viewer viewer;
        viewer.addEventHandler(new osgViewer::StatsHandler);
        viewer.addEventHandler(new osgViewer::WindowSizeHandler);
        viewer.addEventHandler(new osgViewer::ThreadingHandler);

        viewer.realize();
        viewer.setSceneData( root);

        viewer.getCamera()->setFinalDrawCallback(loader);
        loaded=0;

        viewer.run();
    }
} 
```

Here's a link to [my test sample](https://drive.google.com/file/d/0BxIH-jcsgYDdTG5ha21HZE1jX1E/view?usp=sharing)
for ex It fails with following command :

 `OSG_VERTEX_BUFFER_HINT=VAO exename BIGCITY.ive --remove 150 --add 100 `

Note: toggling statshandler ON prevent the crash

**Comment by openscenegraph** [comment]
The callback isn't thread safe and will behave in a very dubious way when handling multiple graphics contexts. So for sure it's a really bad bit of code that and I strongly recommend against writing code like this.  Finalize callbacks aren't meant for adding/removing stuff from the scene graph, it's more abusing than using the OSG.

That being said, by guess is the crash is caused by the callback retaining a reference to scene graph objects in a way that is invisible to the viewer's normal clean up procedures so they don't get clean up properly, so the graphics contexts end up getting deleted prior to the scene graph objects that are still holding references to GL related objects.  

The solution for this type of usage is to implement a releaseGLObjects() method to pass on the releaseGLObjects() to the nested objects.  I've just checked src/osg/Camera.cpp and it's reaseGLObjects() method wasn't calling the draw callbacks as it should so I've added this to the 3.6 branch and 
master.   commit : 645515975734f605e567e9aa195b2c71256f61f2

**Comment by mp3butcher** [comment]
I dont think your guess is right: the crash occurs during the program not at context release..
Further it doesn't occur with VBO path
If you want I could change the Camera::callback with a Node::Callback and set viewer singlethreaded explicitly, but it will not change the outcome....

**Comment by openscenegraph** [comment]
The above code is *awful*.   Casting away const, casting  You are doing lots of things the OSG is trying it's best to prevent you from doing it because it's not a sensible thing to do.  You are abusing the OSG so I if it doesn't work then you are on your own, you absolutely shouldn't be using callbacks like this.

**Comment by mp3butcher** [comment]
I give you all material to reproduce a working behavior with VBO that doesn't work with VAO 
If you dont' want to take 5 min to reproduce it yourself, please don't use these 5 min to  insult my investigations

**Comment by mp3butcher** [comment]
I think i have a lead on that bug:
VA0 with name (says 1)  is deleted then another is regenerated with the same name but lazy vao update don't do anything in this particular case leading to crash
I think the correct way to fix it is to force state.setGlobalVAS on VAO deletion
