### ISSUE TITLE
StreamOperator could kill your system :)

### ISSUE THREAD

**Issue by remoe** [openscenegraph/OpenSceneGraph#738]
When one don't check this failed state here:

https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osgDB/StreamOperator.cpp#L23

It could fill up your log file. We had a 500GB log file because a failed process runs over night :)

**Comment by mp3butcher** [comment]
Er...don't set OSG_NOTIFY_LEVEL to NOTICE for you log system...

**Comment by remoe** [comment]
https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osg/Notify.cpp#L142 ?

**Comment by openscenegraph** [comment]
For an error to be occurring so often as to create a 500GB log suggests you've got some problem elsewhere other than the fact the the OSG's is writing data to a log file.  Resolve the error it's report.  It's not StreamOperator that is dangerous, you are blaming the messenger for the message, not actually addressing the reason for the message which is where the actual problem is.

If you don't care to resolving the errors that are being reported then just set the osg::NotifySeverity to FATAL and it'll ignore all messages lower than FATAL ones.  You can set it programmatically via:

  osg::setNotifyLevel(osg::FATAL);

Or var env vars:

  export OSG_NOTIFY_LEVEL=FATAL.

I'm closing this Issue as StreamOperator is not at fault here, it'll be elsewhere.  If you want assistance on tracking down errors you'll need to provide information like the actual messages being sent to the log.
