### ISSUE TITLE
OcclusionQueryNode _validgeometry breaks backward compatibility

### ISSUE THREAD

**Issue by mp3butcher** [openscenegraph/OpenSceneGraph#810]
query geometry validity added in https://github.com/openscenegraph/OpenSceneGraph/commit/71997fa747f46e54847b2843227d003fb49bb872#diff-5c9d7ea871e2f1816d216fb56fc1a733
can break client code if querygeometry is set manually by user.
Nothing that can't be worked around but still....

**Comment by openscenegraph** [comment]
Ahhhhh... different usage cases that are both fighting each other.  I don't have either usage case to review so can't provide any guidance at this point.  Simply revert the commit will break on usage case in favour on another.  

This does occasionally happen with OSG features and is typically an indication that the underlying design and implementation isn't flexible enough.  It's made more difficult for me to resolve by myself when the original functionality isn't written by me, and it's now a feature I've used another than using the osgocclusionqueury example.  This has meant I've had to rely on those who use the feature to determine what it needs to be fit for purpose.

Ideally we'd have the different usage cases as separate code paths in the OSG example or multiple examples that illustrate the different usage cases so that we can ensure that any changes don't break that particular usage case.  

Hopefully @dan-t who authored the above commit can chip in here.  

I'm open to suggestions on how we can evolve the design+implementation work well in the various usage cases that user require.  At this point I can't do anything as I simply don't have anything to go on, all I know is that one commit required to fix one usage case breaks another.

**Comment by dan-t** [comment]
Ok, for the use case of an user definable query geometry the current API of
`OcclusionQueryNode` is really a bit strange.

I already considered it a bit strange that `QueryGeometry` is accessible
and writable by the user and didn't quite saw the point of it, well, now
I'm seeing it.

A small fix with minimal backward compatibility breakage might be to
remove `osg::QueryGeometry* getQueryGeometry()` and only keep
`const osg::QueryGeometry* getQueryGeometry() const`.

Now add a `void setQueryGeometry(osg::QueryGeometry* geom)` method
that in the case of `geom != nullptr` sets `_validQueryGeometry = true`.

But I don't have the time and use case to test this change by myself.

**Comment by dan-t** [comment]
Thinking a bit further, I don't think that the current implementation of
`OcclusionQueryNode::computeBound` does really handle the user
definable query geometry correctly, because it just overrides the vertex
array of the query geometry, without considering if the geometry was
set by the user.

**Comment by dan-t** [comment]
Instead of the `_validGeometry` boolean there should be an `enum QueryGeometryState`
with the values `Invalid`, `Valid` and `UserDefined`.

`setQueryGeometry` sets the state to `geom ? UserDefined : Invalid`.
`computeBound` only updates the query geometry if `state != UserDefined`.
And the rest of the code only checks for the `Invalid` case.

**Comment by mp3butcher** [comment]
Can I know which use case this commit fixed?
My point of view would be that client code is in charge of disabling OQN when it doesn't have valid child bound....the less we do in oqn the more it will be flexible

**Comment by mp3butcher** [comment]
...@dan-t neverthe less the QGstate might be a good idea, it would also allow not to lock mutex in computebound....

**Comment by dan-t** [comment]
> Can I know which use case this commit fixed?
> 
If I‘m recalling it correctly, the _validGeometry increased the rendering
quality by reducing the flickering when the children of the OcclusionQueryNode
changed.
> My point of view would be that client code is in charge of disabling OQN when it doesn't have valid child bound....the less we do in oqn the more it will be flexible
> 
If the client has to be aware about such things it just gets more error prone.

**Comment by mp3butcher** [comment]
my proposal https://github.com/openscenegraph/OpenSceneGraph/pull/811...

**Comment by dan-t** [comment]
On Mon, Aug 12, 2019 at 09:19:05AM -0700, Julien Valentin wrote:
> my proposal #811...

I don't quite see the point for the compute bound callback, the
`_validQueryGeometry` flag is still needed and it IMHO just further
complicates the design.

The non const `getQueryGeometry` method should be removed, otherwise
the design is just broken and already was before the addition of
the `_validQueryGeometry` flag.

The `Custom` in `setCustomQueryGeometry` doesn't add any further
meaningful information, if the getter of the query geometry is named
`getQueryGeometry` then the setter should be just named `setQueryGeometry`.

The `setQueryGeometry` should handle a nullptr geometry and in this
case switch back to its own internal query geometry.

**Comment by mp3butcher** [comment]
@dan-t plize put your critic on the pr itself else this issue will become unreadable

**Comment by dan-t** [comment]
#813 tries to fix the issue.
