### ISSUE TITLE
Cluster culling callback RTT camera behavior is unintuitive

### ISSUE THREAD

**Issue by Capostrophic** [openscenegraph/OpenSceneGraph#815]
There's [this](https://github.com/openscenegraph/OpenSceneGraph/blob/OpenSceneGraph-3.6/src/osg/ClusterCullingCallback.cpp#L178) line in cluster culling callback implementation.

It was changed in [this](https://github.com/openscenegraph/OpenSceneGraph/commit/f3ce66aa8bfb26ead1edca9307645e2e5bfd5eee) old commit in [an attempt](http://forum.openscenegraph.org/viewtopic.php?t=9214) to improve RTT camera behavior which use this callback by changing getEyePoint() usage to getViewPoint() usage, so basically the same nodes will be (consistently?) culled in any camera.

However, this change is potentially problematic.

The RTT camera's position is not the practical camera position for the callback anymore, which means that what is invisible for the RTT camera is not necessarily culled for that camera, and vice versa.

Now I digress I didn't test it out extensively however this quirk causes real problems in the project I'm contributing to -- e.g. the shadow camera cannot rely on the result of the callback because it inherits the main camera view point but we want to cull stuff that can't go to the shadow map (i.e. isn't visible from the camera's actual position). So this behavior has to be overriden for our goals. But maybe the upstream default behavior is really insufficient?

**Comment by openscenegraph** [comment]
If the features behavior doesn't for your usage case then it would be appropriate to just use your own cluster culling callback that fits, or just remove them.

**Comment by AnyOldName3** [comment]
I don't understand how the current implementation could be useful in any situation, and would welcome someone suggesting one. It says it
> Implements cluster culling to cull back facing subgraphs and drawables.

Surely whether something is back-facing is dependent solely on the camera position, as that's what would be used if we were only using regular triangle-level `GL_CULL_FACE`.

It's my understanding that the inherit-viewpoint system is intended to ensure the same LOD levels get used for RTTs and the main camera and things like that (and that's what we use it for in OpenMW) rather than ensuring two cameras have exactly the same nodes drawn regardless of visibility (as there are other ways that could differ already). If a subgraph faces towards the main view, it doesn't mean it would have any polygons facing an RTT camera, and vice versa.

I think it was a mistake to merge the PR that changed the behaviour, and am really surprised, as I've seen other PRs with much subtler potential flaws get rejected. My guess is that it only helped the user who came up with it because it cancelled out another bug in their application rather than it being the root issue.

Generally, we want to reduce the number of files in our project that are basically just an OSG file with a few lines changed as they're unnecessarily hard to maintain.

**Comment by openscenegraph** [comment]
The ClusterCullingCallback is written for whole earth databases where the
tiles beyond the horizon line can be culled,  It's a very specific usage
case.  It's as much about pulling in the far plane as it is culling data.
It's now a feature that I'd generally use beyond whole earth databases.
The OSG is used by lots of GIS users so this features is for them.

**Comment by AnyOldName3** [comment]
It's a shame it's not configurable, because the pre-3.1 behaviour is *exactly* what we need for culling relatively expensive terrain tiles that can't cast shadows because the sun's too high in the sky or can't be reflected in the water because the player's looking close to downwards. Morrowind is flat, so we don't have a horizon to base the far plane on. The comments in the class imply that our use case was the intended one, at least if you discover it while looking for something that does that, so maybe it should be clarified.
