### ISSUE TITLE
OSG not supported anymore on Android NDK 12

### ISSUE THREAD

**Issue by ThorstenBux** [openscenegraph/OpenSceneGraph#84]
Hi,

as Android NDK dropped the support of the GNU++ compiler with version 11/12 in favour of clang++ it is not possible to use OSG on Android using an up-to-date NDK version. 
Does OSG plan to integrate clang++ support? And when?

Thanks in advance for your reply

**Comment by openscenegraph** [comment]
The OSG already supports Clang,  you just select the appropriate compile using cmake if appropriate the default hasn't already been selected. 

On the Android side I can't comment though as I have no Android build experience.  I would recommend post a comment to the osg-users mailing list/forum to get feedback from the whole community so that those with Android expertise can pitch in how to get things to work.

**Comment by BoiseBaked** [comment]
It's not about the compiler so much, it about the C++ runtime that the OSG binaries are built against and the dreaded "undefined reference to" link errors that occur when linking source, that includes "libc++" header files, compiled to object files with clang++ that targets the "-stdlib=libc++" runtime against the OSG binaries that have not been built using the clang++ compiler, including "libstdc++" header files, and that targets the "stdlib=libstdc++" runtime. Using both clang++ and the "-stdlib=libc++" runtime is required to use C++11 features. The real question is: are there OSG binaries built using clang++, targeting the "-stdlib=libc++" runtime, that supports the C++11 feature set? If not, are there simple, documented steps, to build OSG binaries in this way?

**Comment by BoiseBaked** [comment]
I should have said it this way: it's about ABI compatibility to the C++11 runtime.

**Comment by openscenegraph** [comment]
Please use the osg-users mailling list forum for support questions like these, this is what these are there for not abusing the issue github tracking system.
