### ISSUE TITLE
off-topic: forum.openscenegraph.org is down!

### ISSUE THREAD

**Issue by remoe** [openscenegraph/OpenSceneGraph#860]
It is down since multiple days ...

**Comment by robertosfield** [comment]
The was forum is a community provided facility, that has been hanging by a thread for a while.  The forum website itself is outwith my control, so it's high time moved away from it.  

My preference for forum is to simply use the osg-users googlegroups mirror of the osg-users mailing list.

    https://groups.google.com/forum/#!forum/osg-users

I don't think we'll be able to easily port users across.  I should be able to redirect the forum.openscenegraph.org to the above site though.

Cheers,
Robert.

**Comment by remoe** [comment]
Thanks Robert. I like this old forum. It would be great when it works ;)

**Comment by robertosfield** [comment]
Unfortunately not enough members of the community have not come forward to support it once the original creator moved onto a job where he wasn't using the OSG.  It's been hanging by a thread on old server since.  I don't have the time or expertise to manage the forum, and calls to the community to step up haven't been sufficient.

Without time and effort from the community I think googlegroups is the only viable solution.  If users don't want to use that then then original osg-users mailing list that still works and is low enough maintenance for me to handle.  The googelgroup is just a mirror of this.

**Comment by openscenegraph** [comment]
I have moved the forum.openscenegraph.org URL to point to the osg-users googlegroup.  The googlegroup doesn't the hold the subscriptions that the old forum server had so users will need to subscribe to the googlegroup post, or subscribe to the existing osg-users mailing list that the googlegorup mirrors.

**Comment by remoe** [comment]
And all links indexed by search engines are lost. 
Where are all the other forum groups like submissions?

**Comment by vsg-dev** [comment]
The search engines have always had the mailing list list to search and index, it contained all the same content.  I don't expect anything to be lost.  The osg-users mailing list existed long before the old forum, the old forum just mirrored the mailing list.  The mailing list is definitive source for all discussions over the years.

For submissions we now github PR's and the osg-submissions mailing list.

**Comment by remoe** [comment]
Ok, I'm not a fan of mailing lists. I never used it :)
