### ISSUE TITLE
Crash in the osgfadetext example with OSG 3.6.5

### ISSUE THREAD

**Issue by KimuraRyo** [openscenegraph/OpenSceneGraph#946]
osgText::FadeText does not work after 356e16e.
Empty FrameStamp is referenced in `FadeText::drawImplementation(osg::RenderInfo& renderInfo)`.
I reproduced this using Visual Studio 2017 on Windows 10.

**Comment by openscenegraph** [comment]
Thanks for the note.  I've investigated and found the crash is due to the compile traversal not assigning a FrameStamp as the code assumes and ends up derefercing a nullptr.  I've checked in fixes to master the 3.6 branch:

https://github.com/openscenegraph/OpenSceneGraph/commit/e4373b01439e86623dbda4c4dc27b15c3770d38d
