### ISSUE TITLE
PagedLOD::removeExpiredChildren bug/typo?

### ISSUE THREAD

**Issue by wangii** [openscenegraph/OpenSceneGraph#991]
hi, 
in file PagedLOD.cpp, line 293

```c++
bool PagedLOD::removeExpiredChildren(double expiryTime, unsigned int expiryFrame, NodeList& removedChildren)
{
    if (_children.size()>_numChildrenThatCannotBeExpired)
    {
        unsigned cindex = _children.size() - 1;
        if (!_perRangeDataList[cindex]._filename.empty() &&
            _perRangeDataList[cindex]._timeStamp + _perRangeDataList[cindex]._minExpiryTime < expiryTime &&
            _perRangeDataList[cindex]._frameNumber + _perRangeDataList[cindex]._minExpiryFrames < expiryFrame)
        {
            osg::Node* nodeToRemove = _children[cindex].get();
            removedChildren.push_back(nodeToRemove);
            return Group::removeChildren(cindex,1);
        }
    }
    return false;
}
```
it appears that 
```c++
            _perRangeDataList[cindex]._timeStamp + _perRangeDataList[cindex]._minExpiryTime < expiryTime &&
            _perRangeDataList[cindex]._frameNumber + _perRangeDataList[cindex]._minExpiryFrames < expiryFrame)
```
should be:
```c++
            _perRangeDataList[cindex]._timeStamp + _perRangeDataList[cindex]._minExpiryTime > expiryTime &&
            _perRangeDataList[cindex]._frameNumber + _perRangeDataList[cindex]._minExpiryFrames > expiryFrame)
```

**Comment by openscenegraph** [comment]
The original code looks OK to me.  It's been quite a few years since I
wrote and tested the code so there might be something I'm missing.

Are you just reading the code and thinking that something might be wrong
based on what you think the code is doing, or are you investigating a bug
that is causing a problem?  If so, a means of reproducing the big is where
I'd start with the issue.

**Comment by wangii** [comment]
Thanks for the reply.

I'm working on a custom DatabasePager, and the behavior of `removeExpiredSubgraphs`(line 1759) caused me some confusion:
```C++
    double expiryTime = frameStamp.getReferenceTime() - 0.1;
    unsigned int expiryFrame = frameStamp.getFrameNumber() - 1;
```

I'm not a native speaker but feel semantically if something would be 'expired' (therefore removed) only after the expiry time, instead of before. in the PagedLOD codes, the logic seems to be the opposite. 

It's easy to adapt the logic in PagedLOD but just not feel right.

**Comment by openscenegraph** [comment]
Hi Linan,

Even in my native english I struggle to express logic - C++ is better but
still once it gets complicated enough it can cease to be intuitive.

The expiry should happen for children that have not be visited for period
of time or number of frames. To track things the OSG sets the framestamp
each time a child is visited, if the delta between the current time and the
time of last traversal gets too large then it'll be expired.  The
complication in the implementation is that it does the comparison in
absolution time rather than relative time (duration), so if the childs
record time of last traversal is older (<) the expiry time (which is a
small of back in time from the current time) then it's expired.

I hope this clumsy explanation is sufficient.

**Comment by wangii** [comment]
OK, I get it. the logic is that since the lastTraversalTime/Frame is constantly updated therefore the logic is different than the fixed creation timestamp cases.

thanks for the detailed explanation. hope you are well.
